### ISSUE TITLE
企业微信 参数设置 能详细说下不

### ISSUE THREAD

**Issue by betakernel** [kangwenhang/xiaomisport#7]
企业微信 参数设置 能详细说下不

**Comment by kangwenhang** [comment]
参考http://note.youdao.com/s/HMiudGkb 
corpid就是企业id，corpsecret就是secret

**Comment by betakernel** [comment]
我提取出来 了。填进去。 看日志 提示格式不对

**Comment by betakernel** [comment]
> 参考http://note.youdao.com/s/HMiudGkb
> corpid就是企业id，corpsecret就是secret

我提取出来 。 填进去提示格式不对



企业微信推送参数有误！
Traceback (most recent call last):
已设置为随机步数（***）
  File "main.py", line 325, in <module>
    wxpush(push, sl[0], sl[1], sl[2])
IndexError: list index out of range
1**********7: [2021-08-09 07:01:47] 修改步数（32133）success
Error: Process completed with exit code 1.



@all corpid corpsecret 1000006
@all, corpid, corpsecret, 1000006


请问是哪种填法啊~谢谢~

**Comment by kangwenhang** [comment]
@ALL-corpid-corpsecret-1000006
这种填法，仔细看readme
