### ISSUE TITLE
怎么删除我的提问了？

### ISSUE THREAD

**Issue by betakernel** [kangwenhang/xiaomisport#9]
请问 

企业微信推送 | 推送用户（可@all）-corpid-corpsecret-(agentid 空则为默认1000002)
具体 怎么填进进去啊。。。值知道怎么获取。 我填进去几种方式 都 不行。。。。

能来个模板 不？

**Comment by kangwenhang** [comment]
@all-corpid-corpsecret-agentid不行吗

**Comment by betakernel** [comment]
> @all-corpid-corpsecret-agentid不行吗

不行。空格，逗号，这些都 试过。  步数目前改成功。就是这个通知哈哈。

**Comment by betakernel** [comment]
> @all-corpid-corpsecret-agentid不行吗

见识试了。还是报错。 纳闷了

**Comment by kangwenhang** [comment]
> > @all-corpid-corpsecret-agentid不行吗
> 
> 见识试了。还是报错。 纳闷了

应该还是哪里填错了，我试过，没有问题

**Comment by betakernel** [comment]
> > > @all-corpid-corpsecret-agentid不行吗
> > 
> > 
> > 见识试了。还是报错。 纳闷了
> 
> 应该还是哪里填错了，我试过，没有问题

我晕 。不是我填错了  是因为     我的corpsecret    中间 有个 -   引起   
之前我的corpsecret 是 xxxxxxxxxxxx-vMc 的 这不中间多一个  -  么  

然后 就不行。

我删除 重新建了个新的。   字符间没有这些的。就正常了  
谢谢回复 ~
